remote_theme: daattali/beautiful-jekyll@6.0.1

# Name of website
title: Atelier Noisette

# Your name to show in the footer
author: Heinz Fiedler

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  A propos: "apropos"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/logo.jpeg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true